import beadedJewelry from "../../assets/home/beaded-jewelry.png";
import crochetBag from "../../assets/home/crochet-bag.jpg";
import tissueBox from "../../assets/home/tissue-box.jpg";

export const products = [{
  id: 0, 
  image: beadedJewelry,
  name: 'Beaded Jewelry',
  price: '29.99',
  description: 'Handcrafted beaded jewelry',
},
{
  id: 1, 
  image: crochetBag,
  name: 'Crochet Bag',
  price: '19.99',
  description: 'Handmade crochet bag',
},
{
  id: 2, 
  image: tissueBox,
  name: 'Tissue Box Cover',
  price: '14.99',
  description: 'Beaded tissue box cover',
},
{
  id: 3, 
  image: beadedJewelry,
  name: 'Beaded Jewelry',
  price: '29.99',
  description: 'Handcrafted beaded jewelry',
},
{
  id: 4, 
  image: beadedJewelry,
  name: 'Beaded Jewelry',
  price: '29.99',
  description: 'Handcrafted beaded jewelry',
},
{
  id: 5, 
  image: crochetBag,
  name: 'Crochet Bag',
  price: '19.99',
  description: 'Handmade crochet bag',
},
{
  id: 6, 
  image: tissueBox,
  name: 'Tissue Box Cover',
  price: '14.99',
  description: 'Beaded tissue box cover',
},
{
  id: 7, 
  image: beadedJewelry,
  name: 'Beaded Jewelry',
  price: '29.99',
  description: 'Handcrafted beaded jewelry',
},
{
  id: 8, 
  image: beadedJewelry,
  name: 'Beaded Jewelry',
  price: '29.99',
  description: 'Handcrafted beaded jewelry',
},
{
  id: 9, 
  image: crochetBag,
  name: 'Crochet Bag',
  price: '19.99',
  description: 'Handmade crochet bag',
},
{
  id: 10, 
  image: tissueBox,
  name: 'Tissue Box Cover',
  price: '14.99',
  description: 'Beaded tissue box cover',
},
{
  id: 11, 
  image: beadedJewelry,
  name: 'Beaded Jewelry',
  price: '29.99',
  description: 'Handcrafted beaded jewelry',
},
{
  id: 12, 
  image: beadedJewelry,
  name: 'Beaded Jewelry',
  price: '29.99',
  description: 'Handcrafted beaded jewelry',
},
{
  id: 13, 
  image: crochetBag,
  name: 'Crochet Bag',
  price: '19.99',
  description: 'Handmade crochet bag',
},
{
  id: 14, 
  image: tissueBox,
  name: 'Tissue Box Cover',
  price: '14.99',
  description: 'Beaded tissue box cover',
},
{
  id: 15, 
  image: beadedJewelry,
  name: 'Beaded Jewelry',
  price: '29.99',
  description: 'Handcrafted beaded jewelry',
}];